### ISSUE TITLE
Issue with DEF in 1.5.0_rc1

### ISSUE THREAD

**Issue by danieldelacrua** [oetiker/rrdtool-1.x#581]
If in DEF set vname = "cf" (it's maybe if used cacti and many DS in rra) then rrdtool fail for graph with message: "ERROR: bad CF:"

example:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start=-86400 \
--end=-300 \
--title='temperature' \
--base=1000 \
--height=120 \
--width=800 \
--alt-autoscale-max \
--lower-limit='0' \
--vertical-label='Temperature' \
--slope-mode \
--font TITLE:10: \
--font AXIS:7: \
--font LEGEND:8: \
--font UNIT:7: \
DEF:cf="temperature.rrd":'temp':AVERAGE \
LINE1:cf#0000FFFF:"Temperature"  \
GPRINT:cf:LAST:"Current\:%8.2lf %s"  \
GPRINT:cf:AVERAGE:"Average\:%8.2lf %s"  \
GPRINT:cf:MAX:"Maximum\:%8.2lf %s\n"  \

ERROR: bad CF: temperature.rrd

version 1.4.9 - not have this issue

**Comment by oetiker** [comment]
this is due to the fundamental redisign of the rrdgraph command parser ... it is essentially key value now ... allowing for a mix of key value and positional arguments guess in DEF it is too ambitious

**Comment by oetiker** [comment]
@msperl I think, in order to prevent excessive migration pain, it would be much better if all required positional arguments were parsed as such and did not allow for random key=value to be inserted.

```sh
DEF:cf="temperature.rrd":'temp':AVERAGE
```

gets parsed as expected. Especially the first argument of [CV]?DEF commands seem very susceptible to this problem.

**Comment by msperl** [comment]
We could do that but then you stay "fixed" forever and lose some flexibility.
Maybe something a bit more elaborate would work (not sure what that is right now...)

**Comment by msperl** [comment]
But essentially it would indicate that there is an argument that is not understood...
maybe for those cases we could have a "fallback" parser that tries to run the same thing a second time, but this time with some "escapes" for the first field.

**Comment by oetiker** [comment]
I have been thinking about this a bit ... I think we only need to remove the option of having the second argument being key value in DEF, CDEF and VDEF ... since chances are sort of high that people will run into trouble there ... and this will generate extra support effort ... for all the other arguments, the new approach seems fine ... 

Having this only as a fallback option in case the parsing according to the new rules fails, would certainly be an interesting idea too ... are you in a coding mood?

I have been hesitating to release 1.5.0 as I don't want to get buried by an avalanche of support requests.

**Comment by msperl** [comment]
I'll try to find some time tomorrow... (Sight - Might need to rebuild all the dependencies again...)

**Comment by msperl** [comment]
OK - some review of the code (without compiling) indicates that it should not be so much of an issue for vdef/cdef, because those have (typically) only a single key/value pair and that is immediately "positional" (that is unless I miss something)
So it is mainly "def" that is having issues with keyname-collissions

**Comment by oetiker** [comment]
oh :) so there you did not go 'all the way' I have not yet looked at that code ... so I guess it would be sort of 'in the spirit' if for DEF the first argument was also immediately positional.

**Comment by msperl** [comment]
Actually I did, but as we only have one Key/Value argument (typically) with cdef/vdef it is a non-issue...
only def has that issue where you can parametrize and create key-name collisions...
(not to mention that it was some POC code with known limitations that you took...)

Surprisingly I got rrdtool to compile out of the box on my raspberry pi, so that should speed up the development...

**Comment by oetiker** [comment]
yey ... (and sorry about the POC misunderstanding ... now I know ...  you are the only person I know who turns out so much code just as POC)

**Comment by msperl** [comment]
NP - a solution may come soon
still there would be one caveat with the approach I envision: any additional arguments that are unused would become the "cdef".
so ```def:cf=abc:xxx=file:```
would still take the def name to be ```xxx``` and use ```file``` and not ```cf``` and ```abc```
we can take out some ambiguity, but not all...

**Comment by oetiker** [comment]
... and then throw an error because it has no filename ? wouldn't it be simple to just say the first argument is sort of positional even though it looks like a normal key=value assignement.

**Comment by msperl** [comment]
Got a solution that handles the following:
```
rrdtool graph test.png DEF:cf=test.rrd:temp:AVERAGE LINE1:cf#0000FFFF:"Temperature"
rrdtool graph test.png DEF:rrd=test.rrd:temp:AVERAGE LINE1:rrd#0000FFFF:"Temperature"
rrdtool graph test.png DEF:vname=test.rrd:temp:AVERAGE LINE1:vname#0000FFFF:"Temperature"
```
It is a bit of a "hack" modifying the first positional key name, and rerunning the parser again.

Review the patch here:
https://github.com/msperl/rrdtool-1.x/commit/beeb31409a94ccbf89e81dfcd49c1fc655228ba6
if it seems ok, then I will create a pull-request

**Comment by msperl** [comment]
that is what it actually tries to do - it essentially modifies the first key/value key to something prohibited (and thus unique) and tries to parse it again.
Then it definitely is not any of the "cf", "vname", "rrd",... things and is not "missmatched".

One thing though: this might give some strange errors, so in the error case we maybe should parse  the input a 3rd time to get the error-message correctly (or we keep a copy of the error message and restore it later)...

**Comment by oetiker** [comment]
looks good ... having a sensible error message would be great, as this will reduce the number of confused users :)

**Comment by msperl** [comment]
Created https://github.com/oetiker/rrdtool-1.x/pull/585
it also includes "restoring" the original error and also fixes a "modifying a constant char*" coredump situation

**Comment by msperl** [comment]
note that we should probably add the found issues into the test-suite...

**Comment by oetiker** [comment]
yep that would be great :)
