### ISSUE TITLE
duplicate shared library for 1.5.x and 1.4.x

### ISSUE THREAD

**Issue by iinfo-dev-mk** [oetiker/rrdtool-1.x#714]
First I'm not expert for C development on linux, so maybe problem is on my side.
On my distro - debian 8 jessie - there is package with rrdtool 1.4.8, there is shared library
/usr/lib/librrd.so.4 -> /usr/lib/librrd.so.4.2.1

when I compile rrdtool 1.5.6 from source into $prefix e.g. /opt/rrd15, there is 
/opt/rrd15/librrd.so.4 -> /opt/rrd15/librrd.so.4.3.5

Because there is same shared library name - librrd.so.4, there is possible mistakenly link own code with new library 1.5 and then execute it againts the old one 1.4 without any modification of LD_LIBRARY_PATH. It also happend to me.

When I try to compile and install rrdtool 1.6 - there is different shared library
librrd.so.8 -> librrd.so.8.0.0. When I link my own code with 1.6 and then execute it, I get the warning about unknown shared library librrd.so.8, so then I can fix it with the addition to LD_LIBRARY_PATH and correct shared library is called.

It's possible to change something in source of build scripts for version 1.5 to generate another shared library then librrd.so.4, which has the same name as the default from linux distro package?

**Comment by oetiker** [comment]
The reason for the library being linked to the same file is that the interface has not changed as long as the interface remains stable and only new functionality is added, the major version of the library does not get changed ... 

With 1.6 the whole library was made thread-safe and we also lost some potentially exported symbols ... in a pinch I could have made it still compatible, but I decided to make a break ... hence the new major version ... 

In any event, the safest strategy if you intend to run multiple versions of rrdtool on the same box is to install them into different prefixes and then set `PKG_CONFIG_PATH` to the respective `$PREFIX/lib/pkgconfig` directory when building a tool which you want to use this particular version of rrdtool.

If you are building without `pkg-config` you can also use

`LDFLAGS="-L $PREFIX/lib -Wl,-rpath -Wl,$PREFIX/lib"`

as a linker argument to bake the library path into your application so that there is no need to set `LD_LIBRARY_PATH`.
